testing/config/routes.rb
Rails.application.routes.draw do
  
  
  resources :races
  root to: "dashboard#index"
  get 'dashboard/index'

  get 'dashboard/page1'

  get 'dashboard/page2'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

testing/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

testing/app/models/race.rb
class Race < ApplicationRecord
end

testing/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

testing/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end

  def page1
  end

  def page2
  end
end

testing/app/controllers/races_controller.rb
class RacesController < ApplicationController
  before_action :set_race, only: [:show, :edit, :update, :destroy]

  # GET /races
  # GET /races.json
  def index
    @races = Race.all
  end

  # GET /races/1
  # GET /races/1.json
  def show
  end

  # GET /races/new
  def new
    @race = Race.new
  end

  # GET /races/1/edit
  def edit
  end

  # POST /races
  # POST /races.json
  def create
    @race = Race.new(race_params)

    respond_to do |format|
      if @race.save
        format.html { redirect_to @race, notice: 'Race was successfully created.' }
        format.json { render :show, status: :created, location: @race }
      else
        format.html { render :new }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /races/1
  # PATCH/PUT /races/1.json
  def update
    respond_to do |format|
      if @race.update(race_params)
        format.html { redirect_to @race, notice: 'Race was successfully updated.' }
        format.json { render :show, status: :ok, location: @race }
      else
        format.html { render :edit }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /races/1
  # DELETE /races/1.json
  def destroy
    @race.destroy
    respond_to do |format|
      format.html { redirect_to races_url, notice: 'Race was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_race
      @race = Race.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def race_params
      params.require(:race).permit(:id, :race)
    end
end

testing/app/helpers/application_helper.rb
module ApplicationHelper
end

testing/app/helpers/dashboard_helper.rb
module DashboardHelper
end

testing/app/helpers/races_helper.rb
module RacesHelper
end

testing/app/views/dashboard/page1.html.erb
<h1>Dashboard#page1</h1>
<p>Find me in app/views/dashboard/page1.html.erb</p>

testing/app/views/dashboard/page2.html.erb
<h1>Dashboard#page2</h1>
<p>Find me in app/views/dashboard/page2.html.erb</p>

testing/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testing</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

testing/app/views/races/_form.html.erb
<%= form_for(race) do |f| %>
  <% if race.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(race.errors.count, "error") %> prohibited this race from being saved:</h2>

      <ul>
      <% race.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %>
    <%= f.number_field :id %>
  </div>

  <div class="field">
    <%= f.label :race %>
    <%= f.text_field :race %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

testing/app/views/races/edit.html.erb
<h1>Editing Race</h1>

<%= render 'form', race: @race %>

<%= link_to 'Show', @race %> |
<%= link_to 'Back', races_path %>

testing/app/views/races/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Races</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Race</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @races.each do |race| %>
      <tr>
        <td><%= race.id %></td>
        <td><%= race.race %></td>
        <td><%= link_to 'Show', race %></td>
        <td><%= link_to 'Edit', edit_race_path(race) %></td>
        <td><%= link_to 'Destroy', race, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Race', new_race_path %>

testing/app/views/races/new.html.erb
<h1>New Race</h1>

<%= render 'form', race: @race %>

<%= link_to 'Back', races_path %>

testing/app/views/races/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @race.id %>
</p>

<p>
  <strong>Race:</strong>
  <%= @race.race %>
</p>

<%= link_to 'Edit', edit_race_path(@race) %> |
<%= link_to 'Back', races_path %>